on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: arcdemo8201.azurecr.io
        username: ${{ secrets.acr_arcdemo8201_username }}
        password: ${{ secrets.acr_arcdemo8201_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t arcdemo8201.azurecr.io/shalevaksdemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push arcdemo8201.azurecr.io/shalevaksdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_shalevaksdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep shalev-aks-demo | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace shalev-aks-demo`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: shalev-aks-demo
        container-registry-url: arcdemo8201.azurecr.io
        container-registry-username: ${{ secrets.acr_arcdemo8201_username }}
        container-registry-password: ${{ secrets.acr_arcdemo8201_password }}
        secret-name: shalevaksdemdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: shalev-aks-demo
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          arcdemo8201.azurecr.io/shalevaksdemo:${{ github.sha }}
        imagepullsecrets: |
          shalevaksdemdockerauth
